#!/bin/sh

set -e
cd "$(dirname "$0")"

if command -v pytest > /dev/null; then
  export WARTERAUM_SALT_FILE=./salt.tmp
  export WARTERAUM_TOKENS_FILE=./tokens.tmp

  rm -f valgrind-log.txt "$WARTERAUM_SALT_FILE" "$WARTERAUM_TOKENS_FILE"

  head -c 100 /dev/urandom > "$WARTERAUM_SALT_FILE"

  ../hashtoken "$WARTERAUM_SALT_FILE" random  > "$WARTERAUM_TOKENS_FILE"
  ../hashtoken "$WARTERAUM_SALT_FILE" hannes >> "$WARTERAUM_TOKENS_FILE"
  ../hashtoken "$WARTERAUM_SALT_FILE" lol123 >> "$WARTERAUM_TOKENS_FILE"

  valgrind \
    --log-file=./valgrind-log.txt \
    --leak-check=full \
    --track-origins=yes \
    --show-leak-kinds=all \
    --show-error-list=yes \
    ../warteraum &
  pid=$!

  sleep 3

  pytest -v ./test_integration.py

  kill $pid

  sleep 1

  all_freed=0
  no_errors=0

  grep "All heap blocks were freed" valgrind-log.txt || all_freed=$?
  grep "ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)" valgrind-log.txt || no_errors=$?

  if [[ $all_freed -eq 0 && $no_errors -eq 0 ]]; then
    echo -e "\nvalgrind test: okay"
  else
    echo -e "\nvalgrind test: fail\n"
    cat valgrind-log.txt
    exit 1
  fi
else
  echo "skipped (missing pytest)"
fi
