#!/bin/sh

convert $1 -resize 80x16 -gravity center -background black -extent 80x16 $1.pbm

#pnmsmooth $1.pbm > $1.smooth.pgm
#convert  $1.smooth.pgm  $1.smooth.pbm
#pnminvert $1.smooth.pbm > $1.inv.pbm

pnminvert $1.pbm > $1.inv.pbm
tail -n +3 $1.inv.pbm > $1.bin

dd if=$1.bin skip=0 bs=720 count=1 2>/dev/null | socat - UDP:flipdot.lab:2323 &

