name: "CI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: cachix/install-nix-action@v31.4.1
    - uses: cachix/cachix-action@v16
      with:
        name: openlab-aux
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: nix-build
      run: nix-build
